def RandomSub(records,n):
    """
    The inpur records should be SeqRecord objects. Usually it is an iterator generated by Bio.SeqIO.parse().
    n is the number of output sequences.
    """
    from Bio import SeqIO
    from random import shullfle
    records = SeqIO.to_dict(records)
    identifier = list(records)
    shuffle(identifier)
    sub =[records[ID] for ID in identifier[0:n]]
    return sub
